# Generated by Django 5.1.5 on 2025-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del almacén')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad (en unidades)')),
                ('capacidadOcupada', models.PositiveIntegerField(verbose_name='Capacidad ocupada (en unidades)')),
                ('capacidadDisponible', models.PositiveIntegerField(verbose_name='Capacidad disponible (en unidades)')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
            ],
        ),
    ]
